### ISSUE TITLE
RangeError: recursive issue

### ISSUE THREAD

**Issue by goliatone** [goliatone/gflattener#1]
Original source:

``` js
module.exports = {
    type: 'amqp',
    json: true,
    amqp: require('amqp'),
    exchange: process.env.NODE_AMQP_EXCHANGE,
    client: {
        url: process.env.NODE_AMQP_ENDPOINT
    }
};
```

Solved with:

``` js
module.exports = {
    type: 'amqp',
    json: true,
    exchange: process.env.NODE_AMQP_EXCHANGE,
    client: {
        url: process.env.NODE_AMQP_ENDPOINT
    }
};

module.exports.afterSolver = function(config){
    config.set('amqp.amqp', require('amqp'));
};
```

Error:

```
../project/src/node_modules/flattener/src/flattener.js:68
    Flattener.flatten = function flatten(src, /*private*/ prop, output) {
                                        ^

RangeError: Maximum call stack size exceeded
    at flatten (../project/src/node_modules/flattener/src/flattener.js:68:41)
    at flatten (../project/src/node_modules/flattener/src/flattener.js:84:17)
    at flatten (../project/src/node_modules/flattener/src/flattener.js:84:17)
    at flatten (../project/src/node_modules/flattener/src/flattener.js:84:17)
    at flatten (../project/src/node_modules/flattener/src/flattener.js:84:17)
    at flatten (../project/src/node_modules/flattener/src/flattener.js:84:17)
    at flatten (../project/src/node_modules/flattener/src/flattener.js:84:17)
    at flatten (../project/src/node_modules/flattener/src/flattener.js:84:17)
    at flatten (../project/src/node_modules/flattener/src/flattener.js:84:17)
    at flatten (../project/src/node_modules/flattener/src/flattener.js:84:17)
```

**Comment by goliatone** [comment]
One source was node's `utils` [inherits][1] that would create a cyclical reference.


[1]:https://nodejs.org/api/util.html#util_util_inherits_constructor_superconstructor

**Comment by goliatone** [comment]
This bug resurfaced again, with [sails-mongo](https://github.com/balderdashy/sails-mongo/). Same issue, same "solution"... However it would be nice to figure out what's the issue here.

```js
{'persistence.seedDB': true,
  'persistence.timeout': 30000,
  'persistence.orm.adapters.sails-mongo.identity': 'sails-mongo',
  'persistence.orm.adapters.sails-mongo.adapterApiVersion': 1,
  'persistence.orm.adapters.sails-mongo.defaults.schema': false,
  'persistence.orm.adapters.sails-mongo.datastores': {},
  'persistence.orm.adapters.sails-mongo.mongodb.MongoError.create': {},
  'persistence.orm.adapters.sails-mongo.mongodb.Admin.define.name': 'Admin',
  'persistence.orm.adapters.sails-mongo.mongodb.Admin.define.object.define.name': 'Admin',
  'persistence.orm.adapters.sails-mongo.mongodb.Admin.define.object.define.object.define.name': 'Admin',
  'persistence.orm.adapters.sails-mongo.mongodb.Admin.define.object.define.object.define.object.define.name': 'Admin',
  'persistence.orm.adapters.sails-mongo.mongodb.Admin.define.object.define.object.define.object.define.object.define.name': 'Admin',
  'persistence.orm.adapters.sails-mongo.mongodb.Admin.define.object.define.object.define.object.define.object.define.object.define.name': 'Admin',
  'persistence.orm.adapters.sails-mongo.mongodb.Admin.define.object.define.object.define.object.define.object.define.object.define.object.define.name': 'Admin',
  'persistence.orm.adapters.sails-mongo.mongodb.Admin.define.object.define.object.define.object.define.object.define.object.define.object.define.object.define.name': 'Admin',
  'persistence.orm.adapters.sails-mongo.mongodb.Admin.define.object.define.object.define.object.define.object.define.object.define.object.define.object.define.object.define.name': 'Admin' }
